import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Akimovcg (https://sketchfab.com/akimovcg)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ethereum-3d-logo-de0c154b6f1c46639864a01360dd6aa0
Title: Ethereum 3D logo
*/

export function EthereumModel(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/ethereum_3d_logo.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials['default']}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

// Preload the model to optimize performance
useGLTF.preload('/ethereum_3d_logo.glb');

export default EthereumModel;
